# Use an official Python runtime as the parent image
FROM python:3.8-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements-api.txt

RUN apt-get update && apt-get install -y curl libglib2.0-0 libglib2.0-dev libgl1-mesa-glx

RUN curl -L -o /app/weight.pt "https://drive.google.com/file/d/1kUCA6p_S5Xt6ARF-wiBBjcrXfSaJ25tq/view?ts=6835a4ca"

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run mnist_api.py when the container launches
# CMD ["ls", "/app/"]
CMD ["sh", "-c", "echo 'Starting API' && python -u movies_api.py"]
# CMD ["python", "movies_api.py"]