# Use an official Python runtime as the parent image
FROM python:3.8-slim

# Set the working directory in the container to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app



RUN apt-get update && apt-get install -y unzip curl
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements-gradio.txt 

# RUN curl -L -o /app/weight.pth "https://drive.google.com/uc?export=download&id=1kUCA6p_S5Xt6ARF-wiBBjcrXfSaJ25tq"
# Téléchargement du fichier Drive (avec confirmation)
RUN gdown https://drive.google.com/uc?id=1kUCA6p_S5Xt6ARF-wiBBjcrXfSaJ25tq -O weight.pth

RUN gdown https://drive.google.com/uc?id=1-1OSGlN2EOqyZuehBgpgI8FNOtK-caYf -O data.zip
RUN unzip data.zip && rm data.zip

# Make port 7860 available to the world outside this container
EXPOSE 7860

# Define environment variable for Flask to run in production mode
ENV FLASK_ENV=production

# Run mnist_api.py when the container launches
CMD ["sh", "-c", "echo 'Starting Gradio' && python -u movies_webapp.py"]

